### ISSUE TITLE
originalAnnouncements.toList() 获取数量为0

### ISSUE THREAD

**Issue by yujumpjump** [simple-robot-library/simbot3-website#18]
### 内容描述

群里面是有公告的 但是 获取的时候数量一直为0

**Comment by ForteScarlet** [comment]
官网仓库不受理框架问题反馈，到 [此处](https://github.com/simple-robot/simpler-robot/issues/new?template=bug-report.yml&assignees=ForteScarlet&labels=bug%3F) 反馈
